# Generated by configure — do not edit
ROOT := /crucible
TARGET_OS := openbsd
GO_ENGINE_MODE := shm
CARGO_FEATURES := tls,tls_boring,go_shm_ipc,tls_nss,tls_tomcrypt
CC := cc
PREFIX := /usr/local
WORKER_THREADS := 2
export PATH := /usr/local/bin:/usr/local/sbin:$(HOME)/.cargo/bin:$(PATH)
