/* 由 gen_rack_shim_header.py 从 rack_shim.rb 生成 —— 不要手改。
 * 重新生成：python3 libs/app-engines/rack/gen_rack_shim_header.py
 */
#ifndef CRUCIBLE_RACK_SHIM_RB_H
#define CRUCIBLE_RACK_SHIM_RB_H

static const char rack_shim_rb[] =
    "# Crucible Rack 兼容层 —— 编译进 libapp_rack.so（rack_shim_rb.h），不依赖运行时写文件。\n"
    "#\n"
    "# 目标机上的 libapp_rack.so 用进程内 MRI 嵌入加载 config.ru / index.ru。宿主装了\n"
    "# rack gem 时优先用真正的 Rack::Builder.parse_file；没装（或真 Builder 处理不了\n"
    "# 「裸 lambda」入口）时用这里的 Builder —— 覆盖 run / use / map 的最小子集：\n"
    "#\n"
    "#   run app                        # app 响应 call\n"
    "#   run { |env| [status, {}, []] }\n"
    "#   use Middleware, *args          # 先 use 的包在最外层（Rack 语义）\n"
    "#   map '/prefix' do ... end       # 最长前缀匹配，改写 SCRIPT_NAME/PATH_INFO\n"
    "#   裸 lambda { |env| ... }        # 文件最后一个表达式响应 call 时直接当 app\n"
    "#\n"
    "# 不提供的（需要真 rack gem）：Rack::Request/Response/Utils 等常量、Rack::Lint、\n"
    "# hijack。取舍：目标机装 gem 可能没有网络，内置 Builder 保证 .ru 应用在无 rack\n"
    "# 的宿主上也能真正服务（这是「curl /rack/ 返回 200 且正文来自 index.ru」的关键路径）。\n"
    "#\n"
    "# 失败语义：任何加载/调用异常都向上抛（由 rack_engine.c 用 rb_eval_string_protect\n"
    "# 接住），异常消息/traceback 只进 out->error 供服务端日志，客户端只会看到固定文本。\n"
    "\n"
    "module CrucibleRack\n"
    "  # 响应体上限，与 C 侧/CGI 的 32MiB 约定一致；超过即截断并标注。\n"
    "  MAX_BODY = 32 * 1024 * 1024\n"
    "\n"
    "  # 无 stringio 时用的最小 rack.input（Rack SPEC 要求 gets/each/read/rewind）。\n"
    "  class Input\n"
    "    def initialize(str)\n"
    "      @s = str.to_s.b\n"
    "      @pos = 0\n"
    "    end\n"
    "\n"
    "    def gets\n"
    "      return nil if @pos >= @s.bytesize\n"
    "\n"
    "      nl = @s.index(\"\\n\", @pos)\n"
    "      line = nl ? @s.byteslice(@pos, nl - @pos + 1) : @s.byteslice(@pos..-1)\n"
    "      @pos += line.bytesize\n"
    "      line\n"
    "    end\n"
    "\n"
    "    def read(len = nil, buf = nil)\n"
    "      data = if len.nil?\n"
    "               rest = @s.byteslice(@pos..-1) || ''.b\n"
    "               @pos = @s.bytesize\n"
    "               rest\n"
    "             else\n"
    "               out = @s.byteslice(@pos, len) || ''.b\n"
    "               @pos += out.bytesize\n"
    "               out\n"
    "             end\n"
    "      if buf\n"
    "        buf.replace(data)\n"
    "        buf\n"
    "      else\n"
    "        data\n"
    "      end\n"
    "    end\n"
    "\n"
    "    def each\n"
    "      return enum_for(:each) unless block_given?\n"
    "\n"
    "      while (line = gets)\n"
    "        yield line\n"
    "      end\n"
    "    end\n"
    "\n"
    "    def rewind\n"
    "      @pos = 0\n"
    "      0\n"
    "    end\n"
    "\n"
    "    def close; end\n"
    "  end\n"
    "\n"
    "  # run/use/map 的最小 Rack::Builder 兼容实现。\n"
    "  class Builder\n"
    "    def initialize(&blk)\n"
    "      @use = []\n"
    "      @map = nil\n"
    "      @run = nil\n"
    "      @block_result = nil\n"
    "      return unless blk\n"
    "\n"
    "      ret = instance_eval(&blk)\n"
    "      # 裸 lambda 入口（本目录 config.ru 的写法）：文件最后表达式是可调用对象。\n"
    "      @block_result = ret if ret.respond_to?(:call)\n"
    "    end\n"
    "\n"
    "    def use(mw, *args, &blk)\n"
    "      @use << [mw, args, blk]\n"
    "      self\n"
    "    end\n"
    "\n"
    "    def run(app = nil, &blk)\n"
    "      @run = blk || app\n"
    "      self\n"
    "    end\n"
    "\n"
    "    def map(path, &blk)\n"
    "      raise ArgumentError, 'map 需要 block' unless blk\n"
    "\n"
    "      loc = path.to_s\n"
    "      loc = loc.chomp('/') while loc.length > 1 && loc.end_with?('/')\n"
    "      raise ArgumentError, \"map location 必须以 / 开头（got #{loc.inspect}）\" unless loc.start_with?('/')\n"
    "\n"
    "      @map ||= {}\n"
    "      @map[loc] = Builder.new(&blk).to_app\n"
    "      self\n"
    "    end\n"
    "\n"
    "    def to_app\n"
    "      base = @run || @block_result\n"
    "      app = @map && !@map.empty? ? self.class.build_url_map(base, @map) : base\n"
    "      # Rack 语义：@use 里先 use 的在外层，故反向注入。\n"
    "      @use.reverse_each do |(mw, args, blk)|\n"
    "        app = if mw.respond_to?(:new)\n"
    "                blk ? mw.new(app, *args, &blk) : mw.new(app, *args)\n"
    "              else\n"
    "                mw.call(app, *args)\n"
    "              end\n"
    "      end\n"
    "      raise 'missing run or map statement' if app.nil?\n"
    "\n"
    "      app\n"
    "    end\n"
    "\n"
    "    # map 的最小子集（Rack::URLMap 语义）：最长前缀命中，重写 SCRIPT_NAME/PATH_INFO；\n"
    "    # 无命中时回落 base（config.ru 里 run 的 app），没有 base 就 404。\n"
    "    def self.build_url_map(base, map)\n"
    "      routes = map.keys.sort_by { |p| -p.length }\n"
    "      lambda do |env|\n"
    "        path = env['PATH_INFO'].to_s\n"
    "        hit = routes.find { |p| path == p || path.start_with?(\"#{p}/\") }\n"
    "        if hit.nil?\n"
    "          if base\n"
    "            base.call(env)\n"
    "          else\n"
    "            [404, { 'Content-Type' => 'text/plain; charset=utf-8' }, ['404 Not Found']]\n"
    "          end\n"
    "        else\n"
    "          rest = path[hit.length..-1] || ''\n"
    "          sub_env = env.merge(\n"
    "            'SCRIPT_NAME' => env['SCRIPT_NAME'].to_s + hit,\n"
    "            'PATH_INFO' => rest.empty? ? '/' : rest\n"
    "          )\n"
    "          map[hit].call(sub_env)\n"
    "        end\n"
    "      end\n"
    "    end\n"
    "  end\n"
    "\n"
    "  # 与 Rack::Builder.new_from_string 等价：把源文件包进 Builder 的 block 再 eval，\n"
    "  # 这样 run/use/map 的 self 是 Builder，而脚本里定义的常量仍在 Object 下。\n"
    "  def self.eval_source(src, path)\n"
    "    code = \"CrucibleRack::Builder.new {\\n#{src}\\n}.to_app\"\n"
    "    eval(code, TOPLEVEL_BINDING, path.to_s, 0)\n"
    "  end\n"
    "\n"
    "  def self.eval_file(path)\n"
    "    eval_source(File.read(path), path)\n"
    "  end\n"
    "\n"
    "  # rack gem 可用时优先真 Rack::Builder.parse_file（Rack 3 返回 [app, options]，\n"
    "  # Rack 2 同样是数组）；真 Builder 对「裸 lambda」的 config.ru 会抛\n"
    "  # \"missing run or map statement\" —— 此时回落内置 Builder 再试一次。\n"
    "  def self.load_file(path)\n"
    "    if defined?(::Rack::Builder) && ::Rack::Builder.respond_to?(:parse_file)\n"
    "      begin\n"
    "        r = ::Rack::Builder.parse_file(path)\n"
    "        app = r.is_a?(::Array) ? r[0] : r\n"
    "        return app if app.respond_to?(:call)\n"
    "      rescue ::Exception\n"
    "        # 故意吞掉，转内置 loader；真正的错误由 eval_file 抛出并进 out->error。\n"
    "      end\n"
    "    end\n"
    "    eval_file(path)\n"
    "  end\n"
    "\n"
    "  def self.input_for(body)\n"
    "    @input_class ||= begin\n"
    "      require 'stringio'\n"
    "      StringIO\n"
    "    rescue LoadError, StandardError\n"
    "      Input\n"
    "    end\n"
    "    @input_class.new(body)\n"
    "  end\n"
    "\n"
    "  # 每请求入口（由 C 侧 rb_eval_string_protect(\"CrucibleRack.dispatch($crucible_req)\")）。\n"
    "  # 返回 [status, headers_block, body, note_or_nil]；抛出的异常由 C 侧保护接住。\n"
    "  # 这里自己 rescue 一次是为了**就地**格式化异常（消息+backtrace）写进\n"
    "  # $crucible_last_error：C 侧在 protect 失败后虽然也能读 rb_errinfo，但自己再 eval\n"
    "  # 格式化片段依赖更多 VM 状态，就地格式化最可靠。格式化失败也要保证有固定文本。\n"
    "  def self.dispatch(req)\n"
    "    $crucible_last_error = nil\n"
    "    dispatch_inner(req)\n"
    "  rescue Exception => e\n"
    "    $crucible_last_error = format_exception(e)\n"
    "    raise\n"
    "  end\n"
    "\n"
    "  def self.format_exception(e)\n"
    "    bt = e.backtrace || []\n"
    "    bt = bt.first(20) if bt.respond_to?(:first)\n"
    "    \"#{e.class}: #{e.message}\\n#{bt.join(\"\\n\")}\"\n"
    "  rescue Exception => x\n"
    "    \"ruby exception (unprintable: #{x.class})\"\n"
    "  end\n"
    "\n"
    "  def self.dispatch_inner(req)\n"
    "    script = req['script'].to_s\n"
    "    mtime = begin\n"
    "      File.stat(script).mtime.to_f\n"
    "    rescue SystemCallError\n"
    "      nil\n"
    "    end\n"
    "\n"
    "    if @app.nil? || @app_script != script || @app_mtime != mtime\n"
    "      app = load_file(script)\n"
    "      raise \"rack: #{script} 未返回可调用对象（#{app.class}）\" unless app.respond_to?(:call)\n"
    "\n"
    "      @app = app\n"
    "      @app_script = script\n"
    "      @app_mtime = mtime\n"
    "    end\n"
    "    app = @app\n"
    "\n"
    "    body_in = req['body']\n"
    "    body_in = ''.b if body_in.nil?\n"
    "    method = (req['method'] || 'GET').to_s\n"
    "    path = (req['path'] || '/').to_s\n"
    "    port = (req['server_port'] || '80').to_s\n"
    "    name = (req['server_name'] || 'crucible').to_s\n"
    "    host = port.empty? || port == '80' ? name : \"#{name}:#{port}\"\n"
    "\n"
    "    env = {\n"
    "      'REQUEST_METHOD' => method,\n"
    "      'SCRIPT_NAME' => '',\n"
    "      'PATH_INFO' => path,\n"
    "      'REQUEST_PATH' => path,\n"
    "      'QUERY_STRING' => req['query'].to_s,\n"
    "      'SERVER_NAME' => name,\n"
    "      'SERVER_PORT' => port,\n"
    "      'SERVER_PROTOCOL' => 'HTTP/1.1',\n"
    "      'SERVER_SOFTWARE' => 'crucible/libapp_rack',\n"
    "      'REMOTE_ADDR' => req['remote'].to_s,\n"
    "      'CONTENT_TYPE' => req['content_type'].to_s,\n"
    "      'CONTENT_LENGTH' => req['content_length'].to_s,\n"
    "      'HTTP_HOST' => host,\n"
    "      # Rack 2 SPEC 的版本数组；Rack 3 已不强制该键，中间件兼容起见保留。\n"
    "      'rack.version' => [1, 3],\n"
    "      'rack.url_scheme' => 'http',\n"
    "      'rack.input' => input_for(body_in),\n"
    "      'rack.errors' => $stderr,\n"
    "      'rack.multithread' => false,\n"
    "      'rack.multiprocess' => false,\n"
    "      'rack.run_once' => false,\n"
    "      'rack.hijack?' => false\n"
    "    }\n"
    "\n"
    "    r = app.call(env)\n"
    "    r = r.to_a if !r.is_a?(Array) && r.respond_to?(:to_a)\n"
    "    raise \"rack: 应用返回 #{r.class}（需要 [status, headers, body]）\" unless r.is_a?(Array) && r.size >= 3\n"
    "\n"
    "    status = r[0]\n"
    "    headers = r[1]\n"
    "    body = r[2]\n"
    "    raise \"rack: status 必须是 Integer（got #{status.class}）\" unless status.is_a?(Integer)\n"
    "    raise \"rack: headers 必须是 Hash（got #{headers.class}）\" unless headers.is_a?(Hash)\n"
    "\n"
    "    hdr = ''.b\n"
    "    headers.each do |k, v|\n"
    "      name_s = k.to_s\n"
    "      next if name_s.empty? || name_s.include?(\"\\r\") || name_s.include?(\"\\n\") || name_s.include?(\"\\0\")\n"
    "\n"
    "      (v.is_a?(Array) ? v : [v]).each do |one|\n"
    "        s = one.to_s\n"
    "        next if s.include?(\"\\r\") || s.include?(\"\\n\") || s.include?(\"\\0\")\n"
    "\n"
    "        hdr << name_s.b << ': '.b << s.b << \"\\r\\n\".b\n"
    "      end\n"
    "    end\n"
    "\n"
    "    buf = ''.b\n"
    "    truncated = false\n"
    "    close_body = body.respond_to?(:close)\n"
    "    begin\n"
    "      if body.respond_to?(:each)\n"
    "        body.each do |chunk|\n"
    "          next if chunk.nil?\n"
    "\n"
    "          buf << chunk.to_s.b\n"
    "          if buf.bytesize > MAX_BODY\n"
    "            buf = buf.byteslice(0, MAX_BODY)\n"
    "            truncated = true\n"
    "            break\n"
    "          end\n"
    "        end\n"
    "      elsif body.respond_to?(:call)\n"
    "        buf << body.call.to_s.b\n"
    "        if buf.bytesize > MAX_BODY\n"
    "          buf = buf.byteslice(0, MAX_BODY)\n"
    "          truncated = true\n"
    "        end\n"
    "      elsif !body.nil?\n"
    "        buf << body.to_s.b\n"
    "      end\n"
    "    ensure\n"
    "      body.close if close_body\n"
    "    end\n"
    "\n"
    "    note = nil\n"
    "    if truncated\n"
    "      hdr << \"X-Crucible-Truncated: 1\\r\\n\".b\n"
    "      note = \"rack: 响应体超过 #{MAX_BODY} 字节上限，已截断（script=#{script}）\"\n"
    "    end\n"
    "    [status, hdr, buf, note]\n"
    "  end\n"
    "end\n"
    "\n"
    "# rack gem 可用则用真 Rack；否则补一个最小 Rack::Builder（只在本文件内提供\n"
    "# parse_file/new_from_string，使 config.ru 里的 Rack::Builder.new { ... } 也能用）。\n"
    "begin\n"
    "  require 'rubygems'\n"
    "rescue LoadError, StandardError\n"
    "  nil\n"
    "end\n"
    "begin\n"
    "  require 'rack'\n"
    "  $crucible_have_rack = true\n"
    "rescue LoadError, StandardError\n"
    "  $crucible_have_rack = false\n"
    "end\n"
    "\n"
    "unless defined?(::Rack)\n"
    "  module Rack\n"
    "    class Builder < CrucibleRack::Builder\n"
    "      def self.new_from_string(src, file = '(rackup)')\n"
    "        CrucibleRack.eval_source(src, file)\n"
    "      end\n"
    "\n"
    "      def self.parse_file(path, _opts = nil)\n"
    "        CrucibleRack.eval_file(path)\n"
    "      end\n"
    "    end\n"
    "  end\n"
    "end\n"
    "\n"
    "$crucible_shim_ready = true\n"
    ;

#endif /* CRUCIBLE_RACK_SHIM_RB_H */
