name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Build
        run: |
          cargo build --release --bin webserver --features "tls,tls_boring,go_shm_ipc,tls_nss,tls_tomcrypt" -j 2
      - name: Smoke
        run: echo build-ok
